# Generated by Django 3.2.8 on 2021-11-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='gid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
