# Generated by Django 3.2.9 on 2021-11-25 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_alter_usergroup_gid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeMember',
            fields=[
                ('mid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('face', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='subscribelist',
            name='mem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.subscribemember'),
        ),
    ]
