# Generated by Django 3.2.9 on 2021-12-01 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribe', '0003_auto_20211125_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberGroup',
            fields=[
                ('gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(to='subscribe.SubscribeMember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscribeList',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
