# Generated by Django 3.2.9 on 2021-12-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_auto_20211201_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribemember',
            name='last_profile_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
