# Generated by Django 3.2.9 on 2021-12-16 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0012_dynamicsyncinfo_sync_msg'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineDynamicProcessInfo',
            fields=[
                ('dynamic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dynamic.dynamic')),
                ('process_version', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='timelineentry',
            name='id',
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='dynamic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dynamic.dynamic'),
        ),
    ]
