# Generated by Django 3.2.9 on 2021-12-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_timelineentry_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['event_time'], name='timeline_ti_event_t_485189_idx'),
        ),
    ]
