# Generated by Django 3.2.9 on 2021-11-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('face', models.URLField()),
                ('last_profile_update', models.DateTimeField()),
                ('last_dynamic_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('dynamic_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dynamic_type', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('raw', models.JSONField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.member')),
            ],
        ),
    ]
