# Generated by Django 3.2.9 on 2021-12-03 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_auto_20211201_1316'),
        ('dynamic', '0002_alter_member_last_dynamic_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='subscribe.subscribemember'),
        ),
    ]
