# Generated by Django 3.2.9 on 2021-12-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0005_remove_member_last_profile_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_dynamic_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
