# Generated by Django 3.2.9 on 2021-12-03 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_subscribemember_last_profile_update'),
        ('dynamic', '0006_alter_member_last_dynamic_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='DynamicMember',
        ),
    ]
