# Generated by Django 3.2.9 on 2021-12-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0008_dynamicsyncinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicsyncinfo',
            name='failed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dynamicsyncinfo',
            name='success_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dynamicsyncinfo',
            name='total_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
