# Generated by Django 3.2.9 on 2021-12-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0009_auto_20211204_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='dynamicsyncinfo',
            name='failed_tasks',
        ),
        migrations.RemoveField(
            model_name='dynamicsyncinfo',
            name='success_tasks',
        ),
        migrations.RemoveField(
            model_name='dynamicsyncinfo',
            name='total_tasks',
        ),
        migrations.AddField(
            model_name='dynamicsyncinfo',
            name='failed_tasks',
            field=models.ManyToManyField(related_name='info_failed_tasks', to='dynamic.SyncTask'),
        ),
        migrations.AddField(
            model_name='dynamicsyncinfo',
            name='success_tasks',
            field=models.ManyToManyField(related_name='info_success_tasks', to='dynamic.SyncTask'),
        ),
        migrations.AddField(
            model_name='dynamicsyncinfo',
            name='total_tasks',
            field=models.ManyToManyField(related_name='info_total_tasks', to='dynamic.SyncTask'),
        ),
    ]
