# Generated by Django 3.2.9 on 2021-12-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0011_synctask_fail_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsyncinfo',
            name='sync_msg',
            field=models.TextField(null=True),
        ),
    ]
