name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
          tag=ccr.ccs.tencentyun.com/edrows/ddhelper:$(date +%s)-github-build
          docker build . --file Dockerfile --tag $tag
    - name: Push Docker image
      run: |
          docker login --username=${{ secrets.TQ_ID }} -p ${{ secrets.TQ_PASSWORD }}  ccr.ccs.tencentyun.com
          echo 上传镜像 ccr.ccs.tencentyun.com/edrows/ddhelper:$tag
          sudo docker push ccr.ccs.tencentyun.com/edrows/ddhelper:$tag
